validate skip.json lines 500-600
gardener/test-infra pull request #347
Opened 2021-05-12 19:27 UTC by jfortin-sap

**What this PR does / why we need it**:
Validated 1.20 skip.json lines 500-600, purged no longer found in skip.json and moved working ones to working.json.
**Which issue(s) this PR fixes**:
Fixes #416

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Validated 1.20 skip.json lines 500-600, purged no longer found in skip.json and moved working ones to working.json.
```

2021-05-17 08:34 UTC, dguendisch approved these changes
/lgtm

2021-05-17 16:38 UTC, jfortin-sap commented
@neo-liang-sap Can you merge this? I don't got permissions

2021-05-17 21:21 UTC, neo-liang-sap commented
I don't have write permission to this repo either, @dguendisch @schrodit could you please merge it? thanks!

2021-05-18 06:18 UTC, schrodit requested changes

2021-05-18 06:18 UTC, schrodit commented on integration-tests/e2e/kubetest/description/1.20/working.json
> +  { "testcase": "[sig-storage] In-tree Volumes [Driver: emptydir] [Testpattern: Inline-volume (default fs)] subPath should verify container cannot write to subpath readonly volumes [Slow]"},
there are lot of testcases without a group assigned. 
@dguendisch do you know if we have a test definition for such cases or do they never get executed?

2021-05-19 14:59 UTC, jfortin-sap commented
@dguendisch Ready to merge?

2021-05-31 13:31 UTC, jfortin-sap commented
@schrodit Ready to merge?

2021-06-01 06:17 UTC, schrodit approved these changes
/lgtm

2021-06-01 06:17 UTC, schrodit commented
@jfortin-sap looks good but you have to rebase then I will merge the PR

2021-06-01 20:53 UTC, jfortin-sap commented
@schrodit Re-based

2021-06-02 06:48 UTC, schrodit commented
@jfortin-sap there seems something wrong with your rebase. Now there are ~300 changed files.
Can do you do a `git rebase master` so that only your changes are included in the PR? (Otherwise its hard to judge that it will not overwrite something important)

2021-06-02 14:26 UTC, closed without merging