improve caching and parallel requests
gardener/test-infra pull request #409
Opened 2022-05-24 08:35 UTC by hendrikKahl

**How to categorize this PR?**

/area robustness
/kind enhancement

**What this PR does / why we need it**:
Testmachinery fetches lots of github repositories to resolve test definitions. It already uses a cache but when it is empty or has lots of misses while multiple testruns are processed, multiple requests for the same URI can happen in parallel. 

This causes unnecessary traffic and consumes requests subject to rate-limiting leading to quota exhaustion in the worst case. 

To improve the situation, the number of cache clients will be reduced. Parallel requests to the same URI will wait for the first to succeed and try to obtain the cached answer.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/invite @dguendisch @BeckerMax 

**Release note**:

```other operator
Improve handling of parallel request to avoid exhaustion of request quotas
```

2022-05-30 04:33 UTC, hendrikKahl commented
/hold

2022-06-01 08:51 UTC, hendrikKahl commented
/unhold

2022-06-03 09:47 UTC, BeckerMax commented
/assign

2022-06-20 06:55 UTC, BeckerMax requested changes
Changes already discussed with @hendrikKahl

2022-06-20 06:55 UTC, BeckerMax commented on pkg/testmachinery/ghcache/ratelimitcontrol.go
> +				// no active request yet, we are the first!
Probably best to keep and improve log message. Also true for other log messages.

2022-06-21 05:22 UTC, hendrikKahl commented on pkg/testmachinery/ghcache/ghcache.go
>  func Cache(log logr.Logger, cfg *config.GitHubCache, delegate http.RoundTripper) (http.RoundTripper, error) {
Fair point :) but given that the cache will be initialized only once, I'd rather say it's a "context"-like construct. I've updated the PR, PTLA

2022-06-21 11:30 UTC, BeckerMax approved these changes
thanks!
/lgtm

2022-06-21 11:42 UTC, merged